remote: false

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  Mid-Senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: true
  month: false
  week: false
  24 hours: false

positions:
  - Data Engineer
  - Data Architect
  - Data Solutions
  - Data Manager
  - Snowflake
  - Lead Data Engineer
  - Senior Data Engineer

locations:
  - United States
  - USA

apply_once_at_company: true

distance: 100

company_blacklist:
  - Accenture
  - accenture
  - ACCENTURE

title_blacklist:
  - Sales
  - analyst
  - Data Scientist

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: ollama
llm_model: 'llama3.2:1b'
llm_api_url: 'http://127.0.0.1:11434/'